[workspace]
members = [
    "sim",
    "solver",
    "cli",
]

[workspace.dependencies]
sim = { package = "profit_sim", path = "sim" }
solver = { package = "profit_solver", path = "solver" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
