[package]
name = "profit_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
profit_sim = { path = "../sim" }
profit_solver = { path = "../solver" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
