[package]
name = "profit_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
sim = { workspace = true }
solver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
