[package]
name = "profit_solver"
version = "0.1.0"
edition = "2021"

[dependencies]
sim = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = "0.8.5"
smallvec = "1.10"
