name: Mirroring

on:
  push:
    branches: ['master']

jobs:
  to_uni:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@podium.informatik.uni-siegen.de:ppgrp11
          ssh_private_key:
            ${{ secrets.UNI_PROPRA_SSH_PRIVATE_KEY }}

